# Generated by Django 6.0.1 on 2026-01-30 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_options_task_due_date_task_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(choices=[('purple', 'Фиолетовый'), ('blue', 'Синий'), ('cyan', 'Голубой'), ('green', 'Зеленый'), ('yellow', 'Желтый'), ('orange', 'Оранжевый'), ('red', 'Красный'), ('pink', 'Розовый')], default='purple', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(choices=[('folder', 'Папка'), ('briefcase', 'Портфель'), ('rocket', 'Ракета'), ('star', 'Звезда'), ('heart', 'Сердце'), ('lightning', 'Молния'), ('gear', 'Шестеренка'), ('code', 'Код'), ('palette', 'Палитра'), ('music', 'Музыка'), ('camera', 'Камера'), ('book', 'Книга')], default='folder', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('default', 'По умолчанию'), ('red', 'Красный'), ('orange', 'Оранжевый'), ('yellow', 'Желтый'), ('green', 'Зеленый'), ('cyan', 'Голубой'), ('blue', 'Синий'), ('purple', 'Фиолетовый'), ('pink', 'Розовый')], default='default', max_length=20),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='core.task')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('gray', 'Серый'), ('red', 'Красный'), ('orange', 'Оранжевый'), ('yellow', 'Желтый'), ('green', 'Зеленый'), ('blue', 'Синий'), ('purple', 'Фиолетовый'), ('pink', 'Розовый')], default='blue', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='core.project')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='core.label'),
        ),
    ]
